/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DragRegion: typeof import('./src/components/DragRegion.vue')['default']
    FileList: typeof import('./src/components/FileList.vue')['default']
    IOcticonFileDirectoryOpenFill12: typeof import('~icons/octicon/file-directory-open-fill12')['default']
    IOcticonFileDirectoryOpenFill16: typeof import('~icons/octicon/file-directory-open-fill16')['default']
    IOcticonFileDirectoryOpenFill8: typeof import('~icons/octicon/file-directory-open-fill8')['default']
    IOcticonFold16: typeof import('~icons/octicon/fold16')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
    ToolItem: typeof import('./src/components/ToolItem.vue')['default']
  }
}
